sudo: false
language:
  - php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

cache:
  directories:
    - vendor

install:
  - composer install --no-scripts

script:
  - composer phpcs

notifications:
  email: false
